# Generated by Django 5.0.3 on 2024-03-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='seating_image',
            field=models.URLField(default=''),
        ),
    ]
